### ISSUE TITLE
Ensure DIDs use hash of public key

### ISSUE THREAD

**Issue by dlongley** [veres-one/veres-one#2]
DIDs should use a hash of a public key to represent the unique portion of a DID on Veres One instead of a UUID. This would allow people to onboard DIDs generated privately and used privately for sometime with greater guarantees that no one could have claimed the DID. Once a DID is claimed on Veres One, its keys can obviously be rotated, but on first claim we should ensure that the value of the DID is a hash of a public key on creation (or else reject it).

**Comment by msporny** [comment]
This was implemented a while ago.
