### ISSUE TITLE
Error while scheduling consensus work on worker

### ISSUE THREAD

**Issue by gannan08** [veres-one/veres-one#27]
On startup of a genesis node, two errors get thrown.

https://gist.github.com/gannan08/29a446d61c419a5c024bedf88c844d1d

**Comment by mattcollier** [comment]
Just to qualify this is on *initial* startup right?  aka node bootstrapping?

The error comes from here: https://github.com/digitalbazaar/bedrock-ledger-node/blob/master/lib/consensus.js#L150

Which means something is hitting that function before the collection is initialized which.  We should either prevent that from happening in the first place or catch this error (if it could be considered normal under the circumstances) and suppress it or throw a better, more meaningful, error message.

**Comment by dlongley** [comment]
Closing as stale.
