### ISSUE TITLE
Upgrade Ledger Event and Operation ordering algorithm

### ISSUE THREAD

**Issue by msporny** [veres-one/veres-one#9]
The ledger event and operation ordering algorithm is too naive at present. The ledger data model should be upgraded such that event and operation ordering is explicitly stated by the sender instead of depending on JSON array ordering. This is just a data model cleanup, but important before we go into production.

**Comment by dlongley** [comment]
Event and operation ordering is determined by consensus method, which is `Continuity2017` for the first version of veres one. Closing.
